version: '3.8'
services: 
  traefik: 
    image: traefik
    ports: 
      - 80:80 
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./traefik.yml:/traefik.yml 
      - ./acme.json:/acme.json 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.app.test`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    networks: 
      traefik_network:

networks: 
  traefik_network: 
    name: traefik_net 
    driver: bridge 
    ipam: 
      driver: default